//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMathClient.ServiceReference
{


  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
  [System.ServiceModel.ServiceContractAttribute(Namespace = "www.intertech.com", ConfigurationName = "WFMathClient.ServiceReference.IBasicMath")]
  public interface IBasicMath
  {

    [System.ServiceModel.OperationContractAttribute(Action = "www.intertech.com/IBasicMath/Add", ReplyAction = "www.intertech.com/IBasicMath/AddResponse")]
    int Add(int x, int y);
  }

  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
  public interface IBasicMathChannel : WFMathClient.ServiceReference.IBasicMath, System.ServiceModel.IClientChannel
  {
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
  public partial class BasicMathClient : System.ServiceModel.ClientBase<WFMathClient.ServiceReference.IBasicMath>, WFMathClient.ServiceReference.IBasicMath
  {

    public BasicMathClient()
    {
    }

    public BasicMathClient(string endpointConfigurationName) :
      base(endpointConfigurationName)
    {
    }

    public BasicMathClient(string endpointConfigurationName, string remoteAddress) :
      base(endpointConfigurationName, remoteAddress)
    {
    }

    public BasicMathClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
      base(endpointConfigurationName, remoteAddress)
    {
    }

    public BasicMathClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
      base(binding, remoteAddress)
    {
    }

    public int Add(int x, int y)
    {
      return base.Channel.Add(x, y);
    }
  }
}
